# .|'''''|                               '||\   /||`               '||                          
# || .                                    ||\\.//||                 ||      ''                  
# || |''|| '||''| .|''|, .|''|, `||''|,   ||     ||   '''|.  .|'',  ||''|,  ||  `||''|,  .|''|, 
# ||    ||  ||    ||..|| ||..||  ||  ||   ||     ||  .|''||  ||     ||  ||  ||   ||  ||  ||..|| 
# `|....|' .||.   `|...  `|...  .||  ||. .||     ||. `|..||. `|..' .||  || .||. .||  ||. `|...  
#
# Alacritty config by ABlazingEBoy                                                                               
# Repo: https://github.com/ablazingeboy/GreenMachine-Dotfiles

font:

  size: 12

  normal:
    family: Iosevka Term
    style: Regular

  bold:
    family: Iosevka Term 
    style: Bold

  italic:
    family: Iosevka Term
    style: Italic
    
window:

  padding:
    x: 20
    y: 20

colors:

  primary:
    background: '0x111111'
    foreground: '0xe0e0e0'

  normal:
    black: '0x111111'
    red: '0x4bc98a'
    green: '0x4bc98a'
    yellow: '0x4bc98a'
    blue: '0x4bc98a'
    magenta: '0x4bc98a'
    cyan: '0x4bc98a'
    white: '0xd5d8da'

  bright:
    black: '0x222222'
    red: '0x4bc98a'
    green: '0x4bc98a'
    yellow: '0x4bc98a'
    blue: '0x4bc98a'
    magenta: '0x4bc98a'
    cyan: '0x4bc98a'
    white: '0xd5d8da'
    
cursor:

  style:

    shape: Underline
    blinking: Off
